// <auto-generated />
using System;
using GameServer.datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Models.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("academieLevel")
                        .HasColumnType("int");

                    b.Property<int>("buildingFoodLevel")
                        .HasColumnType("int");

                    b.Property<int>("buildingOilLevel")
                        .HasColumnType("int");

                    b.Property<int>("buildingWoodLevel")
                        .HasColumnType("int");

                    b.Property<int>("entrepotLevel")
                        .HasColumnType("int");

                    b.Property<int>("foodCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("foodLastHarvest")
                        .HasColumnType("datetime2");

                    b.Property<int>("foodProduction")
                        .HasColumnType("int");

                    b.Property<int>("foodQuantity")
                        .HasColumnType("int");

                    b.Property<int>("hqLevel")
                        .HasColumnType("int");

                    b.Property<int>("oilCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("oilLastHarvest")
                        .HasColumnType("datetime2");

                    b.Property<int>("oilProduction")
                        .HasColumnType("int");

                    b.Property<int>("oilQuantity")
                        .HasColumnType("int");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("positionX")
                        .HasColumnType("int");

                    b.Property<int>("positionY")
                        .HasColumnType("int");

                    b.Property<int>("woodCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("woodLastHarvest")
                        .HasColumnType("datetime2");

                    b.Property<int>("woodProduction")
                        .HasColumnType("int");

                    b.Property<int>("woodQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villages");
                });
#pragma warning restore 612, 618
        }
    }
}
